apiVersion: v1
kind: Secret
metadata:
  name: airline-secret
type: Opaque
stringData:
  DB_PASSWORD: "postgres" # In a real scenario, this would be base64 encoded or managed by a vault
  SECRET_KEY: "your_secret_key_here"
